/*
	dx_article_attribute
*/
DROP TABLE IF EXISTS dx_article_attribute;
CREATE TABLE  IF NOT EXISTS `dx_article_attribute` (
  `ARTICLE_ID` BigInt not null,
  `ATTRIBUTE_ID` BIGINT not null,
  `ORD` BigInt not null,
  `ART_ATTRIBUTE_ID` BIGINT not null,
  `ART_ATTRIBUTE_CHOICE_ID` BIGINT null,
  `PUBLIC` TINYINT  not null default 1,
  `MODIF_DT` DATETIME NULL DEFAULT NULL,
  -- DATETIME(6)
  `MODIF_USER_ID` BIGINT NULL DEFAULT NULL,
  `LOCK_INFO` TEXT NULL DEFAULT NULL,
  `LOCK_ID` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ARTICLE_ID`,`ATTRIBUTE_ID`),
  INDEX `ID_ARTICLE_ID` (`ARTICLE_ID`),
  INDEX `ID_ARTICLE_ATTRIBUTE_ID` (`ART_ATTRIBUTE_ID`),
  INDEX `ID_ORD` (`ORD`)
); 



/*
	dx_article_attribute_translation
*/
DROP TABLE IF EXISTS dx_article_attribute_translation;
CREATE TABLE  IF NOT EXISTS `dx_article_attribute_translation` (
  `ARTICLE_ATTRIBUTE_ARTICLE_ID` BigInt not null,
  `ARTICLE_ATTRIBUTE_ATTRIBUTE_ID` BIGINT not null,
  `LANGUAGE_ID` BIGINT not null,
  `NOTES` TEXT  null, 
  `VALUE` JSON not null,
  `MODIF_DT` DATETIME NULL DEFAULT NULL,
  -- DATETIME(6)
  `MODIF_USER_ID` BIGINT NULL DEFAULT NULL,
  `LOCK_INFO` TEXT NULL DEFAULT NULL,
  `LOCK_ID` TEXT NULL DEFAULT NULL,
  `VAL_VIRTUAL` TEXT GENERATED ALWAYS AS (`VALUE` ->> '$.val') STORED,
  PRIMARY KEY (`ARTICLE_ATTRIBUTE_ARTICLE_ID`,`ARTICLE_ATTRIBUTE_ATTRIBUTE_ID`,`LANGUAGE_ID`),
  INDEX `ID_ARTICLE_ATTRIBUTE_ARTICLE_ID` (`ARTICLE_ATTRIBUTE_ARTICLE_ID`),
  INDEX `ID_ARTICLE_ATTRIBUTE_ATTRIBUTE_ID` (`ARTICLE_ATTRIBUTE_ATTRIBUTE_ID`),
  INDEX `ID_LANGUAGE_ID` (`LANGUAGE_ID`),
  FULLTEXT ID_NOTES (NOTES),
  FULLTEXT ID_VAL_VIRTUAL (VAL_VIRTUAL)
);  

/*
	dx_article_attribute_picture
	components
*/
DROP TABLE IF EXISTS dx_article_attribute_picture;
CREATE TABLE  IF NOT EXISTS `dx_article_attribute_picture` (
  `ARTICLE_ID` BigInt not null,
  `ATTRIBUTE_ID` BigInt not null,
  `ART_ATTRIBUTE_ID` BIGINT not null,
  `ORD` BigInt not null,  
  `DATA` LONGBLOB  null,
  `DATE` DATETIME null,
  `NOTES` TEXT null,
  `NAME` TEXT null,
  `ATTRIBUTES` TEXT null,
  `EXTENSION` TEXT null,
  `THUMBNAIL_DATA` LONGBLOB null,
  `THUMBNAIL_ATTRIBUTES` TEXT null,
  `PUBLIC` TINYINT  not null default 1,
  `MODIF_DT` DATETIME NULL DEFAULT NULL,
  -- DATETIME(6)
  `MODIF_USER_ID` BIGINT NULL DEFAULT NULL,
  `LOCK_INFO` TEXT NULL DEFAULT NULL,
  `LOCK_ID` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ARTICLE_ID`,`ATTRIBUTE_ID`),
  INDEX `ID_ARTICLE_ID` (`ARTICLE_ID`),
  INDEX `ID_ART_ATTRIBUTE_ID` (`ART_ATTRIBUTE_ID`),
  INDEX `ID_ORD` (`ORD`) 
);  


/*
	dx_article_attribute_picture_translation
*/
DROP TABLE IF EXISTS dx_article_attribute_picture_translation;
CREATE TABLE  IF NOT EXISTS `dx_article_attribute_picture_translation` (
  `ARTICLE_ATTRIBUTE_PICTURE_ARTICLE_ID` BigInt not null,
  `ARTICLE_ATTRIBUTE_PICTURE_ATTRIBUTE_ID` BIGINT not null,
  `LANGUAGE_ID` BIGINT not null,
  `NOTES` TEXT  null, 
  `MODIF_DT` DATETIME NULL DEFAULT NULL,
  -- DATETIME(6)
  `MODIF_USER_ID` BIGINT NULL DEFAULT NULL,
  `LOCK_INFO` TEXT NULL DEFAULT NULL,
  `LOCK_ID` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ARTICLE_ATTRIBUTE_PICTURE_ARTICLE_ID`,`ARTICLE_ATTRIBUTE_PICTURE_ATTRIBUTE_ID`,`LANGUAGE_ID`),
  INDEX `ID_ARTICLE_ATTRIBUTE_PICTURE_ARTICLE_ID` (`ARTICLE_ATTRIBUTE_PICTURE_ARTICLE_ID`),
  INDEX `ID_ARTICLE_ATTRIBUTE_PICTURE_ATTRIBUTE_ID` (`ARTICLE_ATTRIBUTE_PICTURE_ATTRIBUTE_ID`),
  INDEX `ID_LANGUAGE_ID` (`LANGUAGE_ID`),
  FULLTEXT ID_NOTES (NOTES)
);  

/*
	dx_article
*/
DROP TABLE IF EXISTS dx_article;
CREATE TABLE  IF NOT EXISTS `dx_article` (
  `ID` BigInt not null AUTO_INCREMENT,
  `SALES_UNIT_ID` BigInt null,
  `ACTIVE` TINYINT  null,
  `ARTICLE_TYPE_ID` BigInt not null,
  `CONSINGMENT` TINYINT null default 0,
  `MODIF_DT` DATETIME NULL DEFAULT NULL,
  -- DATETIME(6)
  `MODIF_USER_ID` BIGINT NULL DEFAULT NULL,
  `LOCK_INFO` TEXT NULL DEFAULT NULL,
  `LOCK_ID` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_PK` (`ID`)
);

DROP TABLE IF EXISTS `dx_article_prices`;
CREATE TABLE `dx_article_prices` (
    `ID` BIGINT NOT NULL,
    `ARTICLE_ID` BIGINT NOT NULL,
    `SALES_CHANNEL_ID` BIGINT(20) NOT NULL,
    `VALID_FROM` DATETIME NOT NULL,
    `TAX_CODE_ID` BIGINT NOT NULL,
    `PURCHASE` DECIMAL(15,2) NOT NULL,
    `COST` DECIMAL(15,2) NOT NULL,
    `LIST` DECIMAL(15,2) NOT NULL,
    `RETAIL` DECIMAL(15,2) NOT NULL,
    `REDUCTION` DECIMAL(15,2) NOT NULL,
    `MODIF_DT` DATETIME NULL DEFAULT NULL,
    `MODIF_USER_ID` BIGINT NULL DEFAULT NULL,
    `LOCK_INFO` TEXT NULL DEFAULT NULL,
    `LOCK_ID` TEXT NULL DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE (`ARTICLE_ID`,`SALES_CHANNEL_ID`, `VALID_FROM`)
);